version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: quarterly
    groups:
      safe-dependencies:
        update-types:
          - minor
          - patch
      major-dependencies:
        update-types:
          - major
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    cooldown:
      default-days: 10
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    groups:
      ci-dependencies:
        dependency-type: "production"
    cooldown:
      default-days: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: quarterly
    groups:
      docker-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: deps(docker)
    cooldown:
      default-days: 10
