name: Release Events
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4

      - name: 🚀 Deploy
        uses: ./.github/actions/deploy
        timeout-minutes: 15
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shared_vpc_network: ${{ vars.UGRC_SHARED_VPC_NETWORK_PROD }}
          shared_vpc_subnet: ${{ vars.UGRC_SHARED_VPC_SUBNET_WEST_PROD }}
          env_vars: |-
            APP_ENVIRONMENT=prod

  notify:
    name: Notifications
    runs-on: ubuntu-latest
    needs: deploy-prod
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Release Notifier
        uses: agrc/release-issue-notifications-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
